# Generated by Django 3.2.7 on 2022-03-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20220226_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_benefits_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product benefits description'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product description'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_design_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product design description'),
        ),
    ]
