# Generated by Django 3.2.7 on 2022-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20220329_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_benefits_description',
            field=models.TextField(blank=True, help_text='Enter product benefits description that is to display on product page', null=True, verbose_name='Product benefits description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_description',
            field=models.TextField(blank=True, help_text='Enter product description that is to display on product page', null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_design_description',
            field=models.TextField(blank=True, help_text='Enter product design description that is to display on product page', null=True, verbose_name='Product design description'),
        ),
    ]
