# Generated by Django 3.2.7 on 2022-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_category_product_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Code in 1c'),
        ),
    ]
