# Generated by Django 3.2.7 on 2022-05-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name='Code in 1c'),
        ),
    ]
