# Generated by Django 3.2.7 on 2022-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='external_id',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name='Code in 1c'),
        ),
    ]
