# Generated by Django 3.2.7 on 2022-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_alter_productattribute_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name='Code in 1c'),
        ),
    ]
