# Generated by Django 3.2.7 on 2022-05-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_rename_code_category_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValueAliasMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('alias', models.TextField(blank=True, null=True, verbose_name='Alias')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.productattribute', verbose_name='Attribute value alias mapping')),
            ],
            options={
                'verbose_name': 'Attribute value alias mapping',
                'verbose_name_plural': 'Attribute value alias mappings',
            },
        ),
    ]
