# Generated by Django 3.2.7 on 2022-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_attributevaluealiasmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorHexCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(verbose_name='Text')),
                ('hex_code', models.TextField(blank=True, null=True, verbose_name='Hex code')),
            ],
            options={
                'verbose_name': 'Color hex code',
            },
        ),
        migrations.DeleteModel(
            name='AttributeValueAliasMapping',
        ),
    ]
