# Generated by Django 3.2.7 on 2022-05-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20220523_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhexcode',
            name='color',
            field=models.TextField(unique=True, verbose_name='Text'),
        ),
    ]
