# Generated by Django 3.2.7 on 2022-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_alter_colorhexcode_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhexcode',
            name='color',
            field=models.CharField(max_length=255, unique=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='colorhexcode',
            name='hex_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hex code'),
        ),
    ]
