# Generated by Django 3.2.7 on 2022-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20220527_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhexcode',
            name='color',
            field=models.CharField(help_text='Color name, e.g. black ', max_length=255, unique=True, verbose_name='Color name'),
        ),
        migrations.AlterField(
            model_name='colorhexcode',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Color hex code, e.g. #000000', max_length=255, null=True, verbose_name='Hex code'),
        ),
    ]
