# Generated by Django 3.2.7 on 2024-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_category_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug ES'),
        ),
    ]
