# Generated by Django 3.2.7 on 2024-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_category_slug_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name EN'),
        ),
    ]
