# Generated by Django 3.2.7 on 2024-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_category_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text EN'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Text ES'),
        ),
    ]
