# Generated by Django 3.2.7 on 2024-05-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20240430_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(editable=False, max_length=255)),
                ('value', models.TextField()),
                ('value_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value ES')),
                ('value_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value EN')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.productattribute')),
            ],
        ),
    ]
