# Generated by Django 3.2.7 on 2024-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
