# Generated by Django 3.2.7 on 2024-05-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_alter_attributevalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value external ID'),
        ),
    ]
