# Generated by Django 3.2.7 on 2024-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_productattributevalue_value_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(editable=False, max_length=255)),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('slug_es', models.CharField(max_length=255, verbose_name='Slug ES')),
                ('slug_en', models.CharField(max_length=255, verbose_name='Slug EN')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title ES')),
                ('external_id', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
