# Generated by Django 3.2.7 on 2024-05-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_alter_filter_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(editable=False, max_length=255)),
                ('value_en', models.CharField(max_length=255, verbose_name='Value EN')),
                ('value_es', models.CharField(max_length=255, verbose_name='Value ES')),
                ('slug_en', models.CharField(max_length=255, verbose_name='Slug EN')),
                ('slug_es', models.CharField(max_length=255, verbose_name='Slug ES')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.filter')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.filter')),
                ('filter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.filtervalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
        ),
    ]
