# Generated by Django 3.2.7 on 2024-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_auto_20240508_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='external_id',
            field=models.CharField(help_text='Should be mapped manually to filter field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='slug',
            field=models.CharField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='slug_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Slug EN'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='slug_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Slug ES'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title ES'),
        ),
    ]
