# Generated by Django 3.2.7 on 2024-05-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_auto_20240508_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtervalue',
            name='filter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='catalogue.filter'),
        ),
    ]
