# Generated by Django 3.2.7 on 2024-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_alter_filtervalue_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
