# Generated by Django 3.2.7 on 2024-05-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_auto_20240516_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug ES'),
        ),
    ]
