# Generated by Django 3.2.7 on 2024-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_category_slug_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug EN'),
        ),
    ]
