# Generated by Django 3.2.7 on 2024-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_alter_category_slug_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, null=True, verbose_name='Slug')),
                ('slug_es', models.CharField(max_length=255, null=True, verbose_name='Slug ES')),
                ('slug_en', models.CharField(max_length=255, null=True, verbose_name='Slug EN')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title EN')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Title ES')),
            ],
        ),
    ]
