# Generated by Django 3.2.7 on 2024-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_auto_20240626_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorting',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
