# Generated by Django 3.2.7 on 2024-07-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_sorting_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtervalue',
            name='hex_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hex Code'),
        ),
    ]
