# Generated by Django 3.2.7 on 2024-07-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_filtervalue_hex_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsForExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name='Code in 1c')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
        ),
    ]
