# Generated by Django 3.2.7 on 2024-07-27 15:47

from django.db import migrations


def add_products_to_exchange_list(apps, schema_editor):
    Product = apps.get_model('catalogue', 'Product')
    ProductsForExchange = apps.get_model('catalogue', 'ProductsForExchange')
    for product in Product.objects.filter(structure='parent').all():
        ProductsForExchange.objects.create(
            external_id=product.external_id, product=product)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0061_productsforexchange'),
    ]

    operations = [
        migrations.RunPython(add_products_to_exchange_list, migrations.RunPython.noop)
    ]
