# Generated by Django 3.2.7 on 2022-01-31 06:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='blog/image-preview/%Y/%m')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/image/%Y/%m')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='Manage Popularity')),
            ],
            options={
                'ordering': ['popularity'],
            },
        ),
    ]
