# Generated by Django 3.2.7 on 2022-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_left', models.FileField(upload_to='images/home-banners/')),
                ('image_right', models.FileField(upload_to='images/home-banners/')),
                ('description', models.TextField(blank=True, null=True)),
                ('section_id_selector', models.TextField(help_text='Enter the id selector of banner section without # or leave the field empty to create id automatically', max_length=100, unique=True)),
            ],
        ),
    ]
