# Generated by Django 3.2.7 on 2022-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='homebanner',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Position control'),
        ),
    ]
