# Generated by Django 3.2.7 on 2022-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220826_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='section_id_selector',
            field=models.CharField(help_text='Enter the id selector of banner section without # or leave the field empty to create id automatically', max_length=100, unique=True),
        ),
    ]
