# Generated by Django 3.2.7 on 2022-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homebanner_section_id_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='section_id_selector',
            field=models.CharField(blank=True, help_text='Enter the id selector of banner section without # or leave the field empty to create id automatically', max_length=100, unique=True),
        ),
    ]
