# Generated by Django 3.2.7 on 2022-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchOptimisationFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=254, unique=True, verbose_name='Meta page name')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
            options={
                'verbose_name': 'Search optimisation fields',
                'verbose_name_plural': 'Search optimisation fields',
            },
        ),
    ]
