# Generated by Django 3.2.7 on 2022-08-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_optimisation_fields', '0001_initial'),
    ]

    operations = [
    ]
