# Generated by Django 3.2.7 on 2022-08-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_optimisation_fields', '0002_auto_20220805_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchoptimisationfields',
            name='page_url',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Url of the page'),
        ),
    ]
