# Generated by Django 3.2.7 on 2022-08-07 15:17

from django.db import migrations
from django.core.management import call_command


def add_initial_data(apps, schema_editor):
    call_command('loaddata', './application/search_optimisation_fields/fixtures/add_initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('search_optimisation_fields', '0003_searchoptimisationfields_page_url'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
