# Generated by Django 3.2.7 on 2024-02-29 09:19

from django.db import migrations


def add_stripe_api_key(apps, schema_editor):
    app_settings = apps.get_model('app_settings', 'AppSettings')
    data = {
        'title': 'Stripe API Key',
        'key': 'stripe_api_key',
        'value': '',
        'description': 'Add in value field Stripe API key'
    }
    app_settings_instance = app_settings(**data)
    app_settings_instance.save()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=add_stripe_api_key, reverse_code=reverse_migration)
    ]
