# Generated by Django 3.2.7 on 2022-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewattribute',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='interviewattribute',
            name='title',
        ),
        migrations.AddField(
            model_name='interviewattribute',
            name='question',
            field=models.TextField(default='', help_text='Enter question on the interview page'),
        ),
        migrations.AddField(
            model_name='interviewattribute',
            name='stage',
            field=models.CharField(default='', help_text='Enter the number of the question which is to be displayed on the interview page, e.g. 01', max_length=10, unique=True),
        ),
    ]
