# Generated by Django 3.2.7 on 2022-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20220718_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewattributevalue',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
