# Generated by Django 3.2.7 on 2022-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewattributevalue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewattribute',
            name='facet_title',
            field=models.CharField(default='', help_text='Should be the same as key name value in OSCAR_SEARCH_FACETS settings', max_length=255),
        ),
    ]
