# Generated by Django 3.2.7 on 2022-07-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interviewattribute_facet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewattribute',
            name='slug',
            field=models.SlugField(default='', max_length=255, null=True),
        ),
    ]
