# Generated by Django 3.2.7 on 2022-03-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
        ('partner', '0007_retail_retailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='retailaddress',
            name='website',
            field=models.CharField(blank=True, help_text='Enter web site', max_length=255, verbose_name='Web site'),
        ),
        migrations.AlterField(
            model_name='retailaddress',
            name='retail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.retail'),
        ),
        migrations.CreateModel(
            name='RetailCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country')),
            ],
            options={
                'verbose_name': 'Retail city',
                'verbose_name_plural': 'Retail cities',
            },
        ),
        migrations.AddField(
            model_name='retailaddress',
            name='retail_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.retailcity'),
        ),
    ]
