# Generated by Django 3.2.7 on 2024-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20220321_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='discount_1c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='price_initial_1c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
    ]
